### PR TITLE
Bump version to 1.1.0 and fixed repo url

### PR DESCRIPTION
**Pull request by zehua**
- Starting to use versioning because ramda.github.io depends on it

See https://github.com/ramda/ramda.github.io/pull/190

@buzzdecafe @MattMS @craigdallimore

### CODE REVIEW

**Comment by zehua** [comment]
ping reviewers...

**Comment by zehua** [comment]
ping reviewers again @buzzdecafe

**Comment by zehua** [comment]
@buzzdecafe ping

**Comment by buzzdecafe** [comment]
my apologies!

thanks for the ping

:cow2:

**Comment by zehua** [comment]
Thanks, @buzzdecafe . Could you also help create a tag or release `1.1.0`?

**Pull request merged**
