### PR TITLE
Adding local js

### PR DESCRIPTION
**Pull request by Rafi993**

### CODE REVIEW

**Comment by Rafi993** [comment]
I have created this pull request. We can use it for now. But it would be better if we can create cdnjs for both of those files.

**Comment by CrossEye** [comment]
I think we can use this temporarily.  We need to either add this to a build step or point to some reasonable CDN.  I've been building in-house applications lately and haven't paid a great deal of attention to the CDN world.  Do you have a recommendation?

**Comment by Rafi993** [comment]
cdnjs should do fine for cdn

**Comment by CrossEye** [comment]
Well if we want to continue to include Sanctuary, we'd have to convince them to publish to CDNJS.  Obviously we could get Ramda-Fantasy posted ourselves, but it feels odd for a dead project.  That's why I was wondering what else works more like wzrd.in.  Do you have any experience with https://bundle.run/ for instance?

**Comment by Rafi993** [comment]
If it is a dead project wouldn't it be better to remove it from repl?

**Comment by CrossEye** [comment]
Perhaps, but it's a project we know and control.  Some of the types in there are useful for demos, but really any FantasyLand compatible `Maybe` might be all we need for this.

**Pull request merged**
